### PR TITLE
Fix autocrafter destroying replacement items

### LINKED ISSUE #61: autocrafter: if there isn't enough room in the output inventory, replacements may be lost
expected behavior: crafting should not occur unless there is room for the output and all replacements simultaneously. 

hopefully these images are enough to demonstrate the problem:

image

image

### PR DESCRIPTION
**Pull request by OgelGames**
Simpler version of #69, #70, #71

Works by counting all the output items and replacements, and then comparing that to the space in the `dst` inventory, including partial stacks.

Or to put it a different way, it subtracts the free space from the output items and checks if there is a remainder.

Fixes #61

### CODE REVIEW

**Comment by S-S-X** [comment]
IMO best approach so far.

File: autocrafter.lua [hunk 1]
```diff
@@ -35,16 +35,38 @@ end
 
 local function autocraft(inventory, craft)
 	if not craft then return false end
-	local output_item = craft.output.item
+	local output = craft.output.item
 
 	-- check if we have enough room in dst
-	if not inventory:room_for_item("dst", output_item) then	return false end
+	if not inventory:room_for_item("dst", output) then	return false end
```
Comment (SwissalpS) [inline autocrafter.lua:41]: lines 40 and 41 can be deleted

**Comment by SwissalpS** [comment]
LGTM, passed my manual tests.

**Comment by fluxionary** [comment]
i'll try to review this within the next day or two, but don't wait on me to approve it if it seems right.

**Comment by fluxionary** [comment]
i tested this w/ the firethorn jelly recipe shown in #61, and things seem to work as i expect.
